
services:
  mysql-replication-web:
    build: .
    container_name: mysql-replication-web
    ports:
      - "8000:8000"
    volumes:
      # 挂载数据目录，保存节点信息（包含密码）
      - ./data:/app/data
    # 如要在宿主机修改脚本，可再挂脚本目录：
    # - ./scripts:/app/scripts
    environment:
      - MYSQL_EXTRA_OPTS=--skip-ssl
      - APP_USERNAME=admin
      - APP_PASSWORD=super_safe_password
      - SESSION_SECRET_KEY=random_keys
